### ISSUE TITLE
[proposal] can we add links in pie-chart graphs in the legend section

### ISSUE THREAD

**Issue by sudip10028** [go-echarts/go-echarts#382]
### Describe your proposal

In my usecase i want to add a custom link in every legend so that clicking on the hyperlink any one can be routed to a specific  pages.

### What the feature/improvement it should looks like?

.

### Willing to implement it?

- [ ] Yes, I do

**Comment by Koooooo-7** [comment]
Hi @sudip10028 , I think you can register the `event listener` to achieve this on js level such as `windows.open`, more event type see [events](https://echarts.apache.org/en/api.html#events).
```go
	pie := charts.NewPie()
	const handler = `
   (params) => {
      // I get the legend selected event in Console now
      console.log(params);
   }
`
	pie.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{Title: "label options"}),
		charts.WithEventListeners(event.Listener{
			EventName: "legendselectchanged",
			Handler:   opts.FuncOpts(handler),
		}),
	)

```

**Comment by fingon** [comment]
I don't think this is quite what the original author asked for. SVG has concept of link blocks (see https://www.w3.org/TR/SVG11/linking.html ) and given support for those, it would be much simpler just to produce pure SVG and not JS-driven 'something' (which needs to then map the actual legend selected to url).

**Comment by Koooooo-7** [comment]
> I don't think this is quite what the original author asked for. SVG has concept of link blocks (see https://www.w3.org/TR/SVG11/linking.html ) and given support for those, it would be much simpler just to produce pure SVG and not JS-driven 'something' (which needs to then map the actual legend selected to url).

Hi@fingon.
I think it  may different here since go-echarts is not a PURE raw html generator, it's a wrapper.
On the one hand, although go-echarts supports to generate charts as SVG, there's no a directly api to manipulate it with a link. Additionally, we don't product plain dom/elements by go-echarts, it only creates the echarts instance instead.
On the other hand, the Function/Listener is wrapped by echarts itself. The underlying implementation is not on the go-echarts' layers. Either using the svg functions or js event driven is fine here.
Cos go-echarts' job is done for the echarts instance build and config.
