### ISSUE TITLE
[Bug] Empty xaxis/yaxis dictionary, bar.SetXAxis() is broken

### ISSUE THREAD

**Issue by CaledoniaProject** [go-echarts/go-echarts#405]
### Describe the issue

I copy-pasted these codes from your examples, and it's not generating correct echarts configurations. I copied the output to echart's website and the xAxis is not displayed correctly.

### How to reproduce this issue

Create a new project,

```
package main

import (
	"encoding/json"
	"fmt"
	"math/rand"

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/opts"
)

var (
	itemCnt = 7
	weeks   = []string{"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"}
)

func generateBarItems() []opts.BarData {
	items := make([]opts.BarData, 0)
	for i := 0; i < itemCnt; i++ {
		items = append(items, opts.BarData{Value: rand.Intn(300)})
	}
	return items
}

func barBasic() *charts.Bar {
	bar := charts.NewBar()
	bar.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{Title: "basic bar example", Subtitle: "This is the subtitle."}),
	)

	bar.SetXAxis(weeks).
		AddSeries("Category A", generateBarItems()).
		AddSeries("Category B", generateBarItems())
	return bar
}

func main() {
	a := barBasic()
	b, _ := json.Marshal(a.JSON())
	fmt.Println(string(b))
}
```

Run go get github.com/go-echarts/go-echarts/v2/charts and go-echarts v2.3.3 is installed.

Run go run main.go | jq to extract the JSON content,

```
{"color":["#5470c6","#91cc75","#fac858","#ee6666","#73c0de","#3ba272","#fc8452","#9a60b4","#ea7ccc"],"legend":{},"series":[{"name":"Category A","type":"bar","data":[{"value":270},{"value":260},{"value":220},{"value":26},{"value":205},{"value":42},{"value":77}]},{"name":"Category B","type":"bar","data":[{"value":239},{"value":127},{"value":196},{"value":28},{"value":290},{"value":21},{"value":134}]}],"title":{"text":"basic bar example","subtext":"This is the subtitle."},"toolbox":{},"tooltip":{},"xAxis":[{}],"yAxis":[{}]}
```

And we have an empty xAxis and yAxis. 

### Other information

I copied the configuration to echarts website, https://echarts.apache.org/examples/en/editor.html?c=bar-simple

![shot 2024-02-26 at 10 20 59 AM](https://github.com/go-echarts/go-echarts/assets/1357701/62d077f1-3969-45d9-9e5c-e4f14700813f)

The chart is malformed due to empty xAxis dictionary

### go-echarts version

v2.3.3

**Comment by Koooooo-7** [comment]
Hi @CaledoniaProject ,  if you need the pure JSON options directly.
You need call the `bar.Validate()` before `bar.JSON()` since the `XYAxis` config is post processed in `Validate()`.
```
a := barBasic()
a.Validate()
b, _ := json.Marshal(a.JSON())
```

**Comment by CaledoniaProject** [comment]
Interesting, 

1. why won't go-echarts call Validate() inside JSON()
2. the sample code does not call Validate() and it still works, why is that?

@Koooooo-7

**Comment by Koooooo-7** [comment]
> 1. why won't go-echarts call Validate() inside JSON()

go-echarts does call the `Validate()` before render it to HTML, otherwise, the options gonna be broken as you mentioned above either.

> 2. the sample code does not call Validate() and it still works, why is that?

TBH, at the very beginning, the `Validate()` seems a validation function, somehow it contains some post process stuff also.
And the `JSON()` method is made for template render, it does not meant to be an open api for now.

**Comment by CaledoniaProject** [comment]
@Koooooo-7  Looks like the API needs some refactoring. So if it's not meant to be a public API, should I use json.Marshal() after Validate() ?

**Comment by Koooooo-7** [comment]
> @Koooooo-7 Looks like the API needs some refactoring. So if it's not meant to be a public API, should I use json.Marshal() after Validate() ?

Personally I think works as expect for now, because go-echarts aims to generate echarts styling charts, not being designed to generate echarts' options (and actions, events...etc). so, there is no the sort of export api for getting individual configs for echarts.
The JSON() object more like the mid-product to go-echarts.
If you do wanna the JS options, copying from the generated bar HTML is more reasonable to me.
This way below just plays a trick as a workaround.
```
a := barBasic()
a.Validate()
b, _ := json.Marshal(a.JSON())
```

**Comment by Koooooo-7** [comment]
> @Koooooo-7 Looks like the API needs some refactoring. So if it's not meant to be a public API, should I use json.Marshal() after Validate() ?

Personally I think works as expect for now, because go-echarts aims to generate echarts styling charts, not being designed to generate echarts' options (and actions, events...etc). so, there is no the sort of export api for getting individual configs for echarts.
The JSON() object more like the mid-product to go-echarts.
If you do wanna the JS options, copying from the generated bar HTML is more reasonable to me.
This way below just plays a trick as a workaround.
```
a := barBasic()
a.Validate()
b, _ := json.Marshal(a.JSON())
```

**Comment by CaledoniaProject** [comment]
@Koooooo-7 My situation is a golang server + VUE frontend, I use go-echarts to avoid defining the options structure in golang. I think it's a common usage scenario. It works for now :-)

**Comment by Koooooo-7** [comment]
> @Koooooo-7 My situation is a golang server + VUE frontend, I use go-echarts to avoid defining the options structure in golang. I think it's a common usage scenario. It works for now :-)

Glad to hear that, it should work in basic charts for now.
I think go-echarts could consider provide some export api  in future for echarts options if it needs.
